import React from 'react';

import { Container, InputFileContainer } from './styles';

const Text = ({
  font,
  gray,
  letterSpacing,
  textAlign,
  opacity,
  text,
  flex,
  center,
  small,
  big,
  huge,
  extraHuge,
  darkGray,
  grayDefault,
  lightGray,
  white,
  green,
  red,
  black,
  movBlack,
  movBlack90,
  movPrimary,
  bold,
  semibold,
  lineHeight,
  noWrap,
  capitalize,
  marginTop,
  marginBottom,
  marginLeft,
  marginRight,
  highlight,
  ellipsis,
  hidden,
  width,
  maxLines,
  blue,
  color,
  margin,
  padding,
  height,
  paddingTop,
  paddingLeft,
  paddingBottom,
  paddingRight,
  display,
  type,
  fontFamily,
  ...props
}) => (
  <Container
    {...props}
    type={type}
    paddingBottom={paddingBottom}
    paddingLeft={paddingLeft}
    paddingRight={paddingRight}
    font={font}
    margin={margin}
    padding={padding}
    letterSpacing={letterSpacing}
    textAlign={textAlign}
    opacity={opacity}
    center={center}
    flex={flex}
    small={small}
    big={big}
    huge={huge}
    extraHuge={extraHuge}
    darkGray={darkGray}
    grayDefault={grayDefault}
    gray={gray}
    lightGray={lightGray}
    white={white}
    green={green}
    red={red}
    black={black}
    blue={blue}
    movBlack={movBlack}
    movBlack90={movBlack90}
    movPrimary={movPrimary}
    bold={bold}
    semibold={semibold}
    lineHeight={lineHeight}
    noWrap={noWrap}
    capitalize={capitalize}
    marginTop={marginTop}
    marginBottom={marginBottom}
    marginLeft={marginLeft}
    marginRight={marginRight}
    title={text}
    highlight={highlight}
    ellipsis={ellipsis}
    hidden={hidden}
    width={width}
    maxLines={maxLines}
    color={color}
    height={height}
    paddingTop={paddingTop}
    display={display}
    fontFamily={fontFamily}
  >
    {text}
  </Container>
);

const InputFileText = ({
  font,
  gray,
  letterSpacing,
  textAlign,
  opacity,
  text,
  flex,
  center,
  small,
  big,
  huge,
  extraHuge,
  darkGray,
  grayDefault,
  lightGray,
  white,
  green,
  red,
  black,
  movBlack,
  movBlack90,
  movPrimary,
  bold,
  semibold,
  lineHeight,
  noWrap,
  capitalize,
  marginTop,
  marginBottom,
  marginLeft,
  marginRight,
  highlight,
  ellipsis,
  hidden,
  width,
  maxLines,
  blue,
  color,
  margin,
  padding,
  ...props
}) => (
  <InputFileContainer
    {...props}
    font={font}
    margin={margin}
    padding={padding}
    letterSpacing={letterSpacing}
    textAlign={textAlign}
    opacity={opacity}
    center={center}
    flex={flex}
    small={small}
    big={big}
    huge={huge}
    extraHuge={extraHuge}
    darkGray={darkGray}
    grayDefault={grayDefault}
    gray={gray}
    lightGray={lightGray}
    white={white}
    green={green}
    red={red}
    black={black}
    blue={blue}
    movBlack={movBlack}
    movBlack90={movBlack90}
    movPrimary={movPrimary}
    bold={bold}
    semibold={semibold}
    lineHeight={lineHeight}
    noWrap={noWrap}
    capitalize={capitalize}
    marginTop={marginTop}
    marginBottom={marginBottom}
    marginLeft={marginLeft}
    marginRight={marginRight}
    title={text}
    highlight={highlight}
    ellipsis={ellipsis}
    hidden={hidden}
    width={width}
    maxLines={maxLines}
    color={color}
  >
    {text}
  </InputFileContainer>
);

export { Text, InputFileText };
